package view;

import exception.SaldoInsuficienteException;
import exception.ValorNegativoException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ContaCorrente;
import services.ContaCorrenteService;

public class TabelaContas extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TabelaContas.class.getName());

    final ContaCorrenteService contasService;
    private ContaCorrente contaSelecionada;
    

    public TabelaContas(ContaCorrenteService service) {
        initComponents();

        this.contasService = service;

        carregarContasNaTabela();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaContas = new javax.swing.JTable();
        btnDepositar = new javax.swing.JButton();
        btnSacar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaContas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Numero", "Titular", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaContas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaContasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaContas);

        jScrollPane2.setViewportView(jScrollPane1);

        btnDepositar.setText("Depositar");
        btnDepositar.addActionListener(this::btnDepositarActionPerformed);

        btnSacar.setText("Sacar");
        btnSacar.addActionListener(this::btnSacarActionPerformed);

        btnAdicionar.setText("Adicionar Conta");
        btnAdicionar.addActionListener(this::btnAdicionarActionPerformed);

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(this::btnDeletarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDeletar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSacar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDepositar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdicionar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDepositar)
                    .addComponent(btnSacar)
                    .addComponent(btnAdicionar)
                    .addComponent(btnDeletar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        if (contaSelecionada == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Selecione uma conta primeiro."
            );
            return;
        }

        String valorTexto = JOptionPane.showInputDialog(
                this,
                "Digite o valor do depósito:"
        );

        double valor = Double.parseDouble(valorTexto);

        try {
            contasService.depositar(
                    contaSelecionada.getNumero(),
                    valor
            );

            carregarContasNaTabela();

            JOptionPane.showMessageDialog(
                    this,
                    "Depósito realizado com sucesso!"
            );
        } catch (ValorNegativoException e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        } catch (SQLException ex) {
            System.getLogger(TabelaContas.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnDepositarActionPerformed

    private void tabelaContasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaContasMouseClicked
        int linhaSelecionada = tabelaContas.getSelectedRow();

        if (linhaSelecionada != -1) {
            contaSelecionada = contasService.getContas().get(linhaSelecionada);
        }
    }//GEN-LAST:event_tabelaContasMouseClicked

    private void btnSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarActionPerformed
        if (contaSelecionada == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Selecione uma conta primeiro."
            );
            return;
        }

        String valorTexto = JOptionPane.showInputDialog(
                this,
                "Digite o valor do saque:"
        );

        double valor = Double.parseDouble(valorTexto);

        if (valor <= 0) {
            JOptionPane.showMessageDialog(
                    this,
                    "Digite um valor maior que 0 para sacar.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        try {
            contasService.sacar(
                    contaSelecionada.getNumero(),
                    valor
            );

            carregarContasNaTabela();

            JOptionPane.showMessageDialog(
                    this,
                    "Saque realizado com sucesso!"
            );
        } catch (SaldoInsuficienteException | ValorNegativoException e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        } catch (SQLException ex) {
            System.getLogger(TabelaContas.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnSacarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        if (contaSelecionada == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Selecione uma conta primeiro.",
                    "Atenção",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int resposta = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente excluir a conta "
                + contaSelecionada.getNumero() + "?",
                "Confirmar exclusão",
                JOptionPane.YES_NO_OPTION
        );

        if (resposta == JOptionPane.YES_OPTION) {
            try {
                boolean removida;
                removida = contasService.removerConta(
                        contaSelecionada.getNumero()
                );

                if (removida) {
                    contaSelecionada = null;

                    carregarContasNaTabela();

                    JOptionPane.showMessageDialog(
                            this,
                            "Conta removida com sucesso!"
                    );
                }
            } catch (SQLException ex) {
                System.getLogger(TabelaContas.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        AdicionarConta tela = new AdicionarConta(contasService, this);

        tela.setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnSacar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaContas;
    // End of variables declaration//GEN-END:variables

    protected void carregarContasNaTabela() {

        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("Número");
        modelo.addColumn("Titular");
        modelo.addColumn("Saldo");

        for (ContaCorrente conta : contasService.getContas()) {
            modelo.addRow(new Object[]{
                conta.getNumero(),
                conta.getTitular(),
                conta.getSaldo()
            });
        }

        tabelaContas.setModel(modelo);
    }
}
